# Generated by Django 4.0.4 on 2022-05-26 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniwareMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniware', models.CharField(max_length=70)),
                ('brand', models.CharField(max_length=70)),
                ('headcat', models.CharField(max_length=70)),
                ('subcat', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='UniwareDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('uniware', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='a_models.uniwaremaster')),
            ],
        ),
        migrations.CreateModel(
            name='Inbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('uniware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_models.uniwaremaster')),
            ],
        ),
    ]
