# Generated by Django 4.0.4 on 2022-06-11 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniwaremaster',
            name='productpic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
